/*
----------------------------------------------------------------------------
|  Class: CreateLinkRequestWrapper
|
|  Filename: CreateLinkRequestWrapper.cls
|
|  Author: Umar Mohammad
|
|  Description: JSON to Apex request wrapper for XMR link creation
|      
----------------------------------------------------------------------------
*/
public class CreateLinkRequestWrapper {

	public String callername;	
	public Integer validfor;	
	public String guidanceMode;	
	public String message;	
	public String metadata;	
}
